### ISSUE TITLE
Using values from `config.rb` does not display tasks in web app

### ISSUE THREAD

**Issue by jamespeilunli** [dealingwith/notionpaper#26]
When I run `ruby app.rb` with `config.rb` properly filled, the web app shows that DB ID, filter_property, filter_type, filter_options are all filled with the correct values, but `<div class="tasks">` contains an empty `<ul>` (so the tasks are not displayed).

**Comment by dealingwith** [comment]
@jamespeilunli can you provide a little more detail, it seems to be working for me. Are you sure there were DB records that matched your filters in the config?

<img width="392" alt="Screenshot 2022-11-27 at 6 59 18 PM" src="https://user-images.githubusercontent.com/124208/204170662-aba1aea4-a912-435c-803e-b2d35f0dad60.png">

**Comment by jamespeilunli** [comment]
@dealingwith I was using an invalid DB ID! I put in the correct one, and it's working now. False alarm!
